#include "giotype.h"

//const
//const char *mes[]={"GENNAIO","FEBBRAIO","MARZO","APRILE","MAGGIO","GIUGNO","LUGLIO",
//                     "AGOSTO","SETTEMBRE","OTTOBRE","NOVEMBRE","DICEMBRE"};
const char *gset[]={"Domenica","Lunedi","Martedi","Mercoledi","Giovedi","Venerdi","Sabato",""};

int month[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
info_risorse t_risorse1[100],t_risorse2[100],
	     t_risorse3[100];

info_movimenti tabella_movimenti[100];